### ISSUE TITLE
Required Features

### ISSUE THREAD

**Issue by tathastu871** [liriliri/eruda-android#4]
1) On side of every network request add option to copy it because on android touch selecting and copying is inpossible as we try to select somthing and it selects everything.

2) If possible add "Copy as curl" option for network requests

**Comment by surunzi** [comment]
It's already supported.
![image](https://user-images.githubusercontent.com/3487535/215310841-951cfbc2-9919-4ed6-abfe-9f4b3e5c8f9c.png)
![image](https://user-images.githubusercontent.com/3487535/215310954-123e37ea-7f93-4b0e-b26b-111c2232500b.png)
