### ISSUE TITLE
This is a great app.  You saved my bacon!

### ISSUE THREAD

**Issue by Wozza2014** [liriliri/eruda-android#5]
Hi.

I just wanted to say that this is a great app and thank you for making it.  I'm learning web development on my android tablet and I could not inspect a web page on any browser at all.  I tried Kiwi browser but the inspector is in a different tab and doesn't highlight what you are inspecting.  This app does just that!

Are there any plans in the future to allow editing of the webpage via changing the css in the inspector?

Thanks once again,
Warren.

**Comment by surunzi** [comment]
No plans for future development. But it will be updated when I have free time, although not that much.
